language: cpp
sudo: false

env:
  global:
    - BACKEND=ninja
    - COMMONFLAGS="-Wall -Wextra -pedantic -Werror"
    - PYTHON=python
    - PIP=pip

addons:
  apt:
    sources: &sources
      - boost-latest
      - ubuntu-toolchain-r-test
    packages: &packages
      - libboost1.55-dev
      - libboost-iostreams1.55-dev
      - libboost-program-options1.55-dev
      - ninja-build
      - python-virtualenv

cache:
  apt: true

matrix:
  include:

    # Clang builds

    - compiler: clang
      env: COMPILER=clang++-3.6
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.6
          packages:
            - *packages
            - clang-3.6
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-3.7
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.7
          packages:
            - *packages
            - clang-3.7
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-3.8
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.8
          packages:
            - *packages
            - clang-3.8
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-3.9
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.9
          packages:
            - *packages
            - clang-3.9
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-4.0
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-trusty-4.0
          packages:
            - *packages
            - clang-4.0
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-5.0
      addons: &clang-50
        apt:
          sources:
            - *sources
            - llvm-toolchain-trusty-5.0
          packages:
            - *packages
            - clang-5.0
            - libstdc++-5-dev

    # GCC builds

    - compiler: gcc
      # Something about Travis and/or GCC has issues building in parallel with
      # ninja...
      env: COMPILER=g++-5 BUILD_ARGS="-j1" EXTRAFLAGS=-Wsuggest-override
      addons:
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-5

    - compiler: gcc
      env: COMPILER=g++-6 BUILD_ARGS="-j1" EXTRAFLAGS=-Wsuggest-override
      addons:
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-6

    - compiler: gcc
      env: COMPILER=g++-7 BUILD_ARGS="-j1" EXTRAFLAGS=-Wsuggest-override
      addons: &gcc-7
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-7

    # macOS builds

    - os: osx
      env: PYTHON=python2 PIP=pip2 COMPILER=clang++ BACKEND=ninja

    - os: osx
      env: >
        PYTHON=python2 PIP=pip2 COMPILER=clang++ BACKEND=ninja
        EXTRAFLAGS=-DMETTLE_NO_STDLIB_EXTS

    # Builds with newer versions of Boost

    - compiler: clang
      # Test 1.58 specifically because it has very strict rules for
      # Boost.Variant.
      env: BOOST_VER=1.58 COMPILER=clang++-5.0
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-trusty-5.0
          packages:
            - ninja-build
            - python-virtualenv
            - clang-5.0
            - libstdc++-5-dev
      install:
        - |
          export BOOST_ROOT=$HOME
          wget https://downloads.sourceforge.net/project/boost/boost/1.58.0/boost_1_58_0.tar.bz2
          tar -xjf boost_1_58_0.tar.bz2
          pushd boost_1_58_0
          ./bootstrap.sh --prefix=$HOME --with-libraries=program_options,iostreams
          ./b2 link=shared threading=multi variant=release -d0
          ./b2 install -d0
          popd

    - compiler: clang
      env: BOOST_VER=1.66 COMPILER=clang++-5.0
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-trusty-5.0
          packages:
            - ninja-build
            - python-virtualenv
            - clang-5.0
            - libstdc++-5-dev
      install:
        - |
          export BOOST_ROOT=$HOME
          wget https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2
          tar -xjf boost_1_66_0.tar.bz2
          pushd boost_1_66_0
          ./bootstrap.sh --prefix=$HOME --with-libraries=program_options,iostreams
          ./b2 link=shared threading=multi variant=release -d0
          ./b2 install -d0
          popd

    # Make-backend builds

    - compiler: clang
      env: BACKEND=make COMPILER=clang++-5.0 BUILD_ARGS="-j4"
      addons: *clang-50

    - compiler: gcc
      env: >
        BACKEND=make COMPILER=g++-7 BUILD_ARGS="-j4"
        EXTRAFLAGS=-Wsuggest-override
      addons: *gcc-7

    # Python 3 builds

    - compiler: clang
      env: PYTHON=python3 PIP=pip3 COMPILER=clang++-5.0
      addons: *clang-50

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      shell_session_update() { :; }
      brew update
      brew install ninja
    else
      set -e
      virtualenv env --python=${PYTHON} && source env/bin/activate
    fi
  - ${PIP} install bfg9000
script:
  - >
    CXX=${COMPILER} CPPFLAGS="${COMMONFLAGS} ${EXTRAFLAGS}"
    9k build --vendorize --backend=${BACKEND}
  - cd build
  - ${BACKEND} test ${BUILD_ARGS}
