language: cpp
sudo: false
dist: xenial

env:
  global:
    - BACKEND=ninja
    - COMMONFLAGS="-Wall -Wextra -pedantic -Werror"
    - PYTHON=python
    - PIP=pip

addons:
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
    packages: &packages
      # Test 1.58 specifically because it has very strict rules for
      # Boost.Variant. This is the default in Xenial, but if this changes, we
      # may want to manually install 1.58 to test it.
      - libboost1.58-dev
      - libboost-iostreams1.58-dev
      - libboost-program-options1.58-dev
      - ninja-build
      - python-virtualenv

cache:
  apt: true

matrix:
  include:

    # Clang builds

    - compiler: clang
      env: COMPILER=clang++-3.8
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.8
          packages:
            - *packages
            - clang-3.8
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-3.9
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-precise-3.9
          packages:
            - *packages
            - clang-3.9
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-4.0
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-trusty-4.0
          packages:
            - *packages
            - clang-4.0
            - libstdc++-5-dev

    # Skipping clang 5.0 since it doesn't install properly under Xenial.

    - compiler: clang
      env: COMPILER=clang++-6.0
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-xenial-6.0
          packages:
            - *packages
            - clang-6.0
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-7
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-xenial-7
          packages:
            - *packages
            - clang-7
            - libstdc++-5-dev

    - compiler: clang
      env: COMPILER=clang++-8
      addons: &clang-8
        apt:
          sources:
            - *sources
            - llvm-toolchain-xenial-8
          packages:
            - *packages
            - clang-8
            - libstdc++-5-dev

    # GCC builds

    - compiler: gcc
      # Something about Travis and/or GCC has issues building in parallel with
      # ninja...
      env: COMPILER=g++-5 BUILD_ARGS="-j1" EXTRAFLAGS=-Wsuggest-override
      addons:
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-5

    - compiler: gcc
      env: COMPILER=g++-6 BUILD_ARGS="-j1" EXTRAFLAGS=-Wsuggest-override
      addons:
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-6

    - compiler: gcc
      env: COMPILER=g++-7 BUILD_ARGS="-j1" EXTRAFLAGS=-Wsuggest-override
      addons:
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-7

    - compiler: gcc
      env: COMPILER=g++-8 BUILD_ARGS="-j1" EXTRAFLAGS=-Wsuggest-override
      addons: &gcc-8
        apt:
          sources: *sources
          packages:
            - *packages
            - g++-8

    # macOS builds

    - os: osx
      env: PYTHON=python2 PIP=pip2 COMPILER=clang++ BACKEND=ninja

    - os: osx
      env: >
        PYTHON=python2 PIP=pip2 COMPILER=clang++ BACKEND=ninja
        EXTRAFLAGS=-DMETTLE_NO_STDLIB_EXTS

    # Builds with newer versions of Boost

    - compiler: clang
      env: BOOST_VER=1.67 COMPILER=clang++-8
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-xenial-8
          packages:
            - ninja-build
            - python-virtualenv
            - clang-8
            - libstdc++-5-dev
      install:
        - |
          export BOOST_ROOT=$HOME
          wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2
          tar -xjf boost_1_67_0.tar.bz2
          pushd boost_1_67_0
          ./bootstrap.sh --prefix=$HOME --with-libraries=program_options,iostreams
          ./b2 link=shared threading=multi variant=release -d0
          ./b2 install -d0
          popd

    # C++17 builds

    - compiler: clang
      env: EXTRAOPTS="--std=c++17" COMPILER=clang++-8
      addons:
        apt:
          sources:
            - *sources
            - llvm-toolchain-xenial-8
          packages:
            - *packages
            - clang-8
            - libstdc++-7-dev

    - compiler: gcc
      env: >
        EXTRAOPTS="--std=c++17" COMPILER=g++-8 BUILD_ARGS="-j1"
        EXTRAFLAGS=-Wsuggest-override
      addons: *gcc-8

    # Make-backend builds

    - compiler: clang
      env: BACKEND=make COMPILER=clang++-8 BUILD_ARGS="-j4"
      addons: *clang-8

    - compiler: gcc
      env: >
        BACKEND=make COMPILER=g++-8 BUILD_ARGS="-j4"
        EXTRAFLAGS=-Wsuggest-override
      addons: *gcc-8

    # Python 3 builds

    - compiler: clang
      env: PYTHON=python3 PIP=pip3 COMPILER=clang++-8
      addons: *clang-8

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      shell_session_update() { :; }
      brew update
      brew install ninja
    else
      set -e
      virtualenv env --python=${PYTHON} && source env/bin/activate
    fi
  - ${PIP} install bfg9000
script:
  - >
    CXX=${COMPILER} CPPFLAGS="${COMMONFLAGS} ${EXTRAFLAGS}"
    9k build --vendorize --backend=${BACKEND} ${EXTRAOPTS}
  - cd build
  - ${BACKEND} test ${BUILD_ARGS}
